# Generated by Django 3.0 on 2020-01-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
