# Generated by Django 3.0 on 2020-01-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
    ]
