# Generated by Django 3.0.2 on 2020-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
