# Generated by Django 3.0.2 on 2020-01-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200104_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
